#!/bin/bash

# Simple wrapper for source-building Arch AUR packages.
# TODO: Add additional build options

x=$(pwd)
cd ~/AUR || exit

if [[ $1 =~ "^https" ]]; then
	git clone "$1"
else
	git clone https://aur.archlinux.org/"$1".git
fi

cleanaur=$(echo -n "$1" | cut -d '/' -f4 | cut -d '.' -f1)
cd "$cleanaur" || exit

makepkg -sir
git clean -dfx

cd "$x" || exit
