#!/usr/bin/env bash

GITHUB_USER=$GIT_USER
WORKING_DEV_PATH=$HOME/work/github.com/$GITHUB_USER

if [[ -f "$WORKING_DEV_PATH" ]]; then
	mkdir -p $WORKING_DEV_PATH
fi

packages=(
	base-devel
	cmake
	ninja
	libuv
	libluv
	libutf8proc
	lua
	luajit
	lua-lpeg
	tree-sitter
	ripgrep
	go
	python3
	gettext
	tmux
	parallel
	gh
)

for package in ${packages[@]};do
	install="$install $package"
done

echo "Installing: $install"

if sudo pacman -Syu $install; then
	echo "[devenv] Setup failed.  Error Code: $?"
fi

if [[ ! -d "$WORKING_DEV_PATH" ]]; then
	mkdir -p $WORKING_DEV_PATH
fi

sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
sed -e s/robbyrussell/powerlevel10k/powerlevel10k/ ~/.zshrc
source ~/.zshrc
