#!/usr/bin/env bash

GITHUB_USER=$GIT_USER
WORKING_DEV_PATH=$HOME/work/github.com/$GITHUB_USER

if [[ -f "$WORKING_DEV_PATH" ]]; then
	mkdir -p $WORKING_DEV_PATH
fi

packages=(
	base-devel
	cmake
	ninja
	libuv
	libluv
	libutf8proc
	lua
	luajit
	lua-lpeg
	tree-sitter
	ripgrep
	go
	python3
	gettext
	tmux
	parallel
	wget
	github-cli
	keychain
	zsh
)

echo "Installing: $install"

if ! sudo pacman -Syu --noconfirm --needed ${packages[@]}; then
	echo "[devenv] Setup failed.  Error Code: $?"
fi

if [[ ! -d "$WORKING_DEV_PATH" ]]; then
	mkdir -p $WORKING_DEV_PATH
fi

./straps/00_devenv_shell
